package com.gci.schedule.driverless.bean.bs;

import lombok.Data;

import java.util.Date;

@Data
public class BsEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.EMPLOYEE_ID
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Long employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.VERSION
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.BIRTH_DAY
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Date birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.CONTACT_ADDRESS
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String contactAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.CREATE_USER
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.DATE_CREATED
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Date dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.DWELLING_PLACE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String dwellingPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.EMAIL
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.EMPLOYEE_CODE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.EMPLOYEE_TYPE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String employeeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.IDENTITY_CARD
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String identityCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.LAST_UPDATED
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Date lastUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.MOBILE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.ORGAN_ID
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Long organId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.POST_CODE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.QUALIFICATION
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String qualification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.RECORD_STATUS
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String recordStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.REMARK
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.ROUTE_ID
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Long routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.SEX
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.TELEPHONE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.WRITE_OFF_MAN
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String writeOffMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.WRITE_OFF_TIME
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private Date writeOffTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.PHOTO_NAME
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String photoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.PHOTO_SAVE_NAME
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String photoSaveName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.EMPLOYEE_NUMBER
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String employeeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APTS.BS_EMPLOYEE.PHOTO
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    private String photo;
}