export default {
  retData: {
    total: 1000,
    pageSize: 10,
    list: [
      {
        up_all_passengers: "33",
        fragment: "19:00",
        route_id: "98",
        down_fragment_passengers: "14",
        route_name: "101路",
        up_fragment_passengers: "20",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "2",
        down_all_passengers: "21",
      },
      {
        up_all_passengers: "77",
        fragment: "14:00",
        route_id: "98",
        down_fragment_passengers: "31",
        route_name: "101路",
        up_fragment_passengers: "38",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "4",
        down_all_passengers: "67",
      },
      {
        up_all_passengers: "63",
        fragment: "16:00",
        route_id: "98",
        down_fragment_passengers: "19",
        route_name: "101路",
        up_fragment_passengers: "42",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "4",
        down_all_passengers: "46",
      },
      {
        up_all_passengers: "46",
        fragment: "13:00",
        route_id: "98",
        down_fragment_passengers: "22",
        route_name: "101路",
        up_fragment_passengers: "20",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "3",
        down_all_passengers: "45",
      },
      {
        up_all_passengers: "67",
        fragment: "11:30",
        route_id: "98",
        down_fragment_passengers: "22",
        route_name: "101路",
        up_fragment_passengers: "38",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "2",
        down_all_passengers: "52",
      },
      {
        up_all_passengers: "56",
        fragment: "09:30",
        route_id: "98",
        down_fragment_passengers: "44",
        route_name: "101路",
        up_fragment_passengers: "25",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "2",
        down_all_passengers: "97",
      },
      {
        up_all_passengers: "66",
        fragment: "14:30",
        route_id: "98",
        down_fragment_passengers: "40",
        route_name: "101路",
        up_fragment_passengers: "38",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "4",
        down_all_passengers: "78",
      },
      {
        up_all_passengers: "54",
        fragment: "10:00",
        route_id: "98",
        down_fragment_passengers: "43",
        route_name: "101路",
        up_fragment_passengers: "29",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "2",
        down_all_passengers: "85",
      },
      {
        up_all_passengers: "43",
        fragment: "18:30",
        route_id: "98",
        down_fragment_passengers: "22",
        route_name: "101路",
        up_fragment_passengers: "30",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "3",
        down_all_passengers: "37",
      },
      {
        up_all_passengers: "61",
        fragment: "07:30",
        route_id: "98",
        down_fragment_passengers: "33",
        route_name: "101路",
        up_fragment_passengers: "27",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "2",
        down_all_passengers: "71",
      },
      {
        up_all_passengers: "41",
        fragment: "15:00",
        route_id: "98",
        down_fragment_passengers: "33",
        route_name: "101路",
        up_fragment_passengers: "22",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "3",
        down_all_passengers: "69",
      },
      {
        up_all_passengers: "51",
        fragment: "09:00",
        route_id: "98",
        down_fragment_passengers: "36",
        route_name: "101路",
        up_fragment_passengers: "32",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "3",
        down_all_passengers: "85",
      },
      {
        up_all_passengers: "54",
        fragment: "17:00",
        route_id: "98",
        down_fragment_passengers: "40",
        route_name: "101路",
        up_fragment_passengers: "28",
        pdate: "2024-04-29",
        down_trips: "5",
        up_trips: "2",
        down_all_passengers: "70",
      },
      {
        up_all_passengers: "16",
        fragment: "20:30",
        route_id: "98",
        down_fragment_passengers: "16",
        route_name: "101路",
        up_fragment_passengers: "8",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "2",
        down_all_passengers: "25",
      },
      {
        up_all_passengers: "24",
        fragment: "21:30",
        route_id: "98",
        down_fragment_passengers: "8",
        route_name: "101路",
        up_fragment_passengers: "15",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "3",
        down_all_passengers: "11",
      },
      {
        up_all_passengers: "77",
        fragment: "07:00",
        route_id: "98",
        down_fragment_passengers: "33",
        route_name: "101路",
        up_fragment_passengers: "40",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "4",
        down_all_passengers: "59",
      },
      {
        up_all_passengers: "26",
        fragment: "20:00",
        route_id: "98",
        down_fragment_passengers: "13",
        route_name: "101路",
        up_fragment_passengers: "14",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "3",
        down_all_passengers: "23",
      },
      {
        up_all_passengers: "19",
        fragment: "12:30",
        route_id: "98",
        down_fragment_passengers: "13",
        route_name: "101路",
        up_fragment_passengers: "8",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "1",
        down_all_passengers: "22",
      },
      {
        up_all_passengers: "3",
        fragment: "22:30",
        route_id: "98",
        down_fragment_passengers: "3",
        route_name: "101路",
        up_fragment_passengers: "2",
        pdate: "2024-04-29",
        down_trips: "1",
        up_trips: "1",
        down_all_passengers: "4",
      },
      {
        up_all_passengers: "79",
        fragment: "11:00",
        route_id: "98",
        down_fragment_passengers: "20",
        route_name: "101路",
        up_fragment_passengers: "35",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "2",
        down_all_passengers: "53",
      },
      {
        up_all_passengers: "90",
        fragment: "17:30",
        route_id: "98",
        down_fragment_passengers: "48",
        route_name: "101路",
        up_fragment_passengers: "59",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "3",
        down_all_passengers: "67",
      },
      {
        up_all_passengers: "31",
        fragment: "12:00",
        route_id: "98",
        down_fragment_passengers: "17",
        route_name: "101路",
        up_fragment_passengers: "21",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "2",
        down_all_passengers: "39",
      },
      {
        up_all_passengers: "17",
        fragment: "21:00",
        route_id: "98",
        down_fragment_passengers: "4",
        route_name: "101路",
        up_fragment_passengers: "12",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "2",
        down_all_passengers: "6",
      },
      {
        up_all_passengers: "18",
        fragment: "08:30",
        route_id: "98",
        down_fragment_passengers: "10",
        route_name: "101路",
        up_fragment_passengers: "9",
        pdate: "2024-04-29",
        down_trips: "1",
        up_trips: "2",
        down_all_passengers: "10",
      },
      {
        up_all_passengers: "67",
        fragment: "16:30",
        route_id: "98",
        down_fragment_passengers: "37",
        route_name: "101路",
        up_fragment_passengers: "32",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "3",
        down_all_passengers: "66",
      },
      {
        up_all_passengers: "42",
        fragment: "15:30",
        route_id: "98",
        down_fragment_passengers: "32",
        route_name: "101路",
        up_fragment_passengers: "21",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "2",
        down_all_passengers: "66",
      },
      {
        up_all_passengers: "8",
        fragment: "22:00",
        route_id: "98",
        down_fragment_passengers: "1",
        route_name: "101路",
        up_fragment_passengers: "6",
        pdate: "2024-04-29",
        down_trips: "1",
        up_trips: "1",
        down_all_passengers: "2",
      },
      {
        up_all_passengers: "18",
        fragment: "06:30",
        route_id: "98",
        down_fragment_passengers: "12",
        route_name: "101路",
        up_fragment_passengers: "8",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "2",
        down_all_passengers: "16",
      },
      {
        up_all_passengers: "82",
        fragment: "10:30",
        route_id: "98",
        down_fragment_passengers: "43",
        route_name: "101路",
        up_fragment_passengers: "41",
        pdate: "2024-04-29",
        down_trips: "3",
        up_trips: "3",
        down_all_passengers: "87",
      },
      {
        up_all_passengers: "19",
        fragment: "08:00",
        route_id: "98",
        down_fragment_passengers: "32",
        route_name: "101路",
        up_fragment_passengers: "8",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "1",
        down_all_passengers: "51",
      },
      {
        up_all_passengers: "44",
        fragment: "13:30",
        route_id: "98",
        down_fragment_passengers: "20",
        route_name: "101路",
        up_fragment_passengers: "19",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "2",
        down_all_passengers: "43",
      },
      {
        up_all_passengers: "17",
        fragment: "06:00",
        route_id: "98",
        down_fragment_passengers: "12",
        route_name: "101路",
        up_fragment_passengers: "10",
        pdate: "2024-04-29",
        down_trips: "5",
        up_trips: "2",
        down_all_passengers: "17",
      },
      {
        up_all_passengers: "65",
        fragment: "18:00",
        route_id: "98",
        down_fragment_passengers: "14",
        route_name: "101路",
        up_fragment_passengers: "45",
        pdate: "2024-04-29",
        down_trips: "1",
        up_trips: "2",
        down_all_passengers: "19",
      },
      {
        up_all_passengers: "58",
        fragment: "19:30",
        route_id: "98",
        down_fragment_passengers: "14",
        route_name: "101路",
        up_fragment_passengers: "29",
        pdate: "2024-04-29",
        down_trips: "2",
        up_trips: "3",
        down_all_passengers: "26",
      },
    ],
    pageNum: 1,
  },
  retCode: 0,
  retMsg: "OK",
};

export const dayFlowResponse = {
  retData: {
    total: 2000,
    pageSize: 10,
    list: [
      {
        station_name: "大南路站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10002278",
        night_load_factor: "0.151",
        station_order: "8",
        flat_load_factor: "0.076",
        direction: "0",
        mor_load_factor: "0.09",
      },
      {
        station_name: "大南路站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10002276",
        night_load_factor: "0.119",
        station_order: "7",
        flat_load_factor: "0.187",
        direction: "1",
        mor_load_factor: "0.142",
      },
      {
        station_name: "中山图书馆站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10004345",
        night_load_factor: "0.118",
        station_order: "9",
        flat_load_factor: "0.12",
        direction: "1",
        mor_load_factor: "0.113",
      },
      {
        station_name: "起义路口站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10003935",
        night_load_factor: "0.114",
        station_order: "6",
        flat_load_factor: "0.142",
        direction: "1",
        mor_load_factor: "0.12",
      },
      {
        station_name: "文明路站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10000504",
        night_load_factor: "0.122",
        station_order: "8",
        flat_load_factor: "0.2",
        direction: "1",
        mor_load_factor: "0.127",
      },
      {
        station_name: "文明路站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10000503",
        night_load_factor: "0.164",
        station_order: "7",
        flat_load_factor: "0.071",
        direction: "0",
        mor_load_factor: "0.067",
      },
      {
        station_name: "解放中路站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10005696",
        night_load_factor: "0.173",
        station_order: "9",
        flat_load_factor: "0.049",
        direction: "0",
        mor_load_factor: "0.079",
      },
      {
        station_name: "解放中路站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10009500",
        night_load_factor: "0.116",
        station_order: "5",
        flat_load_factor: "0.09",
        direction: "1",
        mor_load_factor: "0.12",
      },
      {
        station_name: "白云路东站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10002447",
        night_load_factor: "0.123",
        station_order: "3",
        flat_load_factor: "0.093",
        direction: "0",
        mor_load_factor: "0.105",
      },
      {
        station_name: "越秀南路站",
        route_id: "98",
        route_name_run: "101路",
        date_time: "2024-04-29 09:15:23.982899000",
        station_id: "10001396",
        night_load_factor: "0.153",
        station_order: "5",
        flat_load_factor: "0.073",
        direction: "0",
        mor_load_factor: "0.075",
      },
    ],
    pageNum: 1,
  },
  retCode: 0,
  retMsg: "OK",
};
