package com.gci.schedule.driverless.dynamic.bean;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class StationPassenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.PDATE
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name="pdate", format = "yyyy-MM-dd HH:mm:ss")
    private Date pdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.ROUTE_NAME_RUN
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "route_name_run")
    private String routeNameRun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.STATION_ID
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "station_id")
    private Long stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.STATION_NAME
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "station_name")
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.DIRECTION
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "direction")
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.ORDER_NUMBER
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "order_number")
    private Long orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.PHOUR
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "phour")
    private Short phour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.PMINUTE
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "pminute")
    private String pminute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.UP_PASSENGERS
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "upcount")
    private Integer upcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.DOWN_PASSENGERS
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "downcount")
    private Integer downcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.CUR_PASSENGERS
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "curpeople")
    private Integer curpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DY_STATION_PASSENGER.ROUTE_ID
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    @JSONField(name = "route_id_run")
    private Long routeIdRun;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.PDATE
     *
     * @return the value of DY_STATION_PASSENGER.PDATE
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public Date getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.PDATE
     *
     * @param pdate the value for DY_STATION_PASSENGER.PDATE
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.ROUTE_NAME_RUN
     *
     * @return the value of DY_STATION_PASSENGER.ROUTE_NAME_RUN
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public String getRouteNameRun() {
        return routeNameRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.ROUTE_NAME_RUN
     *
     * @param routeNameRun the value for DY_STATION_PASSENGER.ROUTE_NAME_RUN
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setRouteNameRun(String routeNameRun) {
        this.routeNameRun = routeNameRun == null ? null : routeNameRun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.STATION_ID
     *
     * @return the value of DY_STATION_PASSENGER.STATION_ID
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public Long getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.STATION_ID
     *
     * @param stationId the value for DY_STATION_PASSENGER.STATION_ID
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setStationId(Long stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.STATION_NAME
     *
     * @return the value of DY_STATION_PASSENGER.STATION_NAME
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.STATION_NAME
     *
     * @param stationName the value for DY_STATION_PASSENGER.STATION_NAME
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.DIRECTION
     *
     * @return the value of DY_STATION_PASSENGER.DIRECTION
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public String getDirection() {
        return direction;
    }
    
    public int getDirectionInt() {
        return Integer.valueOf(direction);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.DIRECTION
     *
     * @param direction the value for DY_STATION_PASSENGER.DIRECTION
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.ORDER_NUMBER
     *
     * @return the value of DY_STATION_PASSENGER.ORDER_NUMBER
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public Long getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.ORDER_NUMBER
     *
     * @param orderNumber the value for DY_STATION_PASSENGER.ORDER_NUMBER
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setOrderNumber(Long orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.PHOUR
     *
     * @return the value of DY_STATION_PASSENGER.PHOUR
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public Short getPhour() {
        return phour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.PHOUR
     *
     * @param phour the value for DY_STATION_PASSENGER.PHOUR
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setPhour(Short phour) {
        this.phour = phour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_STATION_PASSENGER.PMINUTE
     *
     * @return the value of DY_STATION_PASSENGER.PMINUTE
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public String getPminute() {
        return pminute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_STATION_PASSENGER.PMINUTE
     *
     * @param pminute the value for DY_STATION_PASSENGER.PMINUTE
     *
     * @mbg.generated Thu May 23 14:26:18 CST 2019
     */
    public void setPminute(String pminute) {
        this.pminute = pminute == null ? null : pminute.trim();
    }


    public Integer getUpcount() {
        return upcount;
    }

    public void setUpcount(Integer upcount) {
        this.upcount = upcount;
    }

    public Integer getDowncount() {
        return downcount;
    }

    public void setDowncount(Integer downcount) {
        this.downcount = downcount;
    }

    public Integer getCurpeople() {
        return curpeople;
    }

    public void setCurpeople(Integer curpeople) {
        this.curpeople = curpeople;
    }

    public Long getRouteIdRun() {
        return routeIdRun;
    }

    public void setRouteIdRun(Long routeIdRun) {
        this.routeIdRun = routeIdRun;
    }
}