package com.gci.schedule.driverless.bean.scheduleD;

import java.util.Date;

//进出站详情
public class AdrealSimulate implements Cloneable {

    private Long id;

    private Long routeId;

    private String routeCode;

    private Long routeStaId;

    private String routeStaName;

    private String adFlag; //进/出站标识 0出站;1进站

    private Date adTime;

    private Long scheduleId; //计划ID

    private Short upNumber; //上车人数

    private Short downNumber; //下车人数

    private Short currentNumber; //车内人数

    private Short fullLoadRatio; //满载率

    private String busCode; //车辆编码

    private String startDirection; //出车方向(0:上行;1:下行)

    private Short startOrderNumber; //出车车位

    private  Integer  busId;

    private  String  busName;

    private String busNameFull;//车辆全称

    private String serviceType;

    private String serviceName;

    private  Integer notLongBusSum ; //非全程巴士总数

    private  Integer  runTimeNum ;//时间段，6点是12，6点半是13

    private  Integer direction; //方向

    private Boolean singleBus;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.ID
     *
     * @param id the value for DY_ADREAL_SIMULATE.ID
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.ROUTE_ID
     *
     * @return the value of DY_ADREAL_SIMULATE.ROUTE_ID
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Long getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.ROUTE_ID
     *
     * @param routeId the value for DY_ADREAL_SIMULATE.ROUTE_ID
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setRouteId(Long routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.ROUTE_CODE
     *
     * @return the value of DY_ADREAL_SIMULATE.ROUTE_CODE
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public String getRouteCode() {
        return routeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.ROUTE_CODE
     *
     * @param routeCode the value for DY_ADREAL_SIMULATE.ROUTE_CODE
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setRouteCode(String routeCode) {
        this.routeCode = routeCode == null ? null : routeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.ROUTE_STA_ID
     *
     * @return the value of DY_ADREAL_SIMULATE.ROUTE_STA_ID
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Long getRouteStaId() {
        return routeStaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.ROUTE_STA_ID
     *
     * @param routeStaId the value for DY_ADREAL_SIMULATE.ROUTE_STA_ID
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setRouteStaId(Long routeStaId) {
        this.routeStaId = routeStaId;
    }


    public String getRouteStaName() {
        return routeStaName;
    }

    public void setRouteStaName(String routeStaName) {
        this.routeStaName = routeStaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.AD_FLAG
     *
     * @return the value of DY_ADREAL_SIMULATE.AD_FLAG
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public String getAdFlag() {
        return adFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.AD_FLAG
     *
     * @param adFlag the value for DY_ADREAL_SIMULATE.AD_FLAG
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setAdFlag(String adFlag) {
        this.adFlag = adFlag == null ? null : adFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.AD_TIME
     *
     * @return the value of DY_ADREAL_SIMULATE.AD_TIME
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Date getAdTime() {
        return adTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.AD_TIME
     *
     * @param adTime the value for DY_ADREAL_SIMULATE.AD_TIME
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setAdTime(Date adTime) {
        this.adTime = adTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.SCHEDULE_ID
     *
     * @return the value of DY_ADREAL_SIMULATE.SCHEDULE_ID
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Long getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.SCHEDULE_ID
     *
     * @param scheduleId the value for DY_ADREAL_SIMULATE.SCHEDULE_ID
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setScheduleId(Long scheduleId) {
        this.scheduleId = scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.UP_NUMBER
     *
     * @return the value of DY_ADREAL_SIMULATE.UP_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Short getUpNumber() {
        return upNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.UP_NUMBER
     *
     * @param upNumber the value for DY_ADREAL_SIMULATE.UP_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setUpNumber(Short upNumber) {
        this.upNumber = upNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.DOWN_NUMBER
     *
     * @return the value of DY_ADREAL_SIMULATE.DOWN_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Short getDownNumber() {
        return downNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.DOWN_NUMBER
     *
     * @param downNumber the value for DY_ADREAL_SIMULATE.DOWN_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setDownNumber(Short downNumber) {
        this.downNumber = downNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.CURRENT_NUMBER
     *
     * @return the value of DY_ADREAL_SIMULATE.CURRENT_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Short getCurrentNumber() {
        return currentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.CURRENT_NUMBER
     *
     * @param currentNumber the value for DY_ADREAL_SIMULATE.CURRENT_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setCurrentNumber(Short currentNumber) {
        this.currentNumber = currentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.FULL_LOAD_RATIO
     *
     * @return the value of DY_ADREAL_SIMULATE.FULL_LOAD_RATIO
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Short getFullLoadRatio() {
        return fullLoadRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.FULL_LOAD_RATIO
     *
     * @param fullLoadRatio the value for DY_ADREAL_SIMULATE.FULL_LOAD_RATIO
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setFullLoadRatio(Short fullLoadRatio) {
        this.fullLoadRatio = fullLoadRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.BUS_CODE
     *
     * @return the value of DY_ADREAL_SIMULATE.BUS_CODE
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public String getBusCode() {
        return busCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.BUS_CODE
     *
     * @param busCode the value for DY_ADREAL_SIMULATE.BUS_CODE
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setBusCode(String busCode) {
        this.busCode = busCode == null ? null : busCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.START_DIRECTION
     *
     * @return the value of DY_ADREAL_SIMULATE.START_DIRECTION
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public String getStartDirection() {
        return startDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.START_DIRECTION
     *
     * @param startDirection the value for DY_ADREAL_SIMULATE.START_DIRECTION
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setStartDirection(String startDirection) {
        this.startDirection = startDirection == null ? null : startDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DY_ADREAL_SIMULATE.START_ORDER_NUMBER
     *
     * @return the value of DY_ADREAL_SIMULATE.START_ORDER_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public Short getStartOrderNumber() {
        return startOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DY_ADREAL_SIMULATE.START_ORDER_NUMBER
     *
     * @param startOrderNumber the value for DY_ADREAL_SIMULATE.START_ORDER_NUMBER
     *
     * @mbg.generated Mon Apr 22 16:20:16 CST 2019
     */
    public void setStartOrderNumber(Short startOrderNumber) {
        this.startOrderNumber = startOrderNumber;
    }

    public Integer getBusId() {
        return busId;
    }

    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    public String getBusName() {
        return busName;
    }

    public void setBusName(String busName) {
        this.busName = busName;
    }

    public String getBusNameFull() {
        return busNameFull;
    }

    public void setBusNameFull(String busNameFull) {
        this.busNameFull = busNameFull;
    }

    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public Integer getNotLongBusSum() {
        return notLongBusSum;
    }

    public void setNotLongBusSum(Integer notLongBusSum) {
        this.notLongBusSum = notLongBusSum;
    }

    public Integer getRunTimeNum() {
        return runTimeNum;
    }

    public void setRunTimeNum(Integer runTimeNum) {
        this.runTimeNum = runTimeNum;
    }

    public Integer getDirection() {
        return direction;
    }

    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    public Boolean getSingleBus() {
        return singleBus;
    }

    public void setSingleBus(Boolean singleBus) {
        this.singleBus = singleBus;
    }

    public Object clone() {
        try {
            return super.clone();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}