package com.gci.schedule.driverless.bean.scheduleD;

import cn.hutool.core.convert.Convert;
import com.fasterxml.jackson.annotation.JsonIgnore;

public class RouteWasteTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REP_ROUTE_WASTE_TIME.ROUTE_ID
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
	@JsonIgnore
    private Long routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REP_ROUTE_WASTE_TIME.RUN_DAY_NUM
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
	@JsonIgnore
    private String runDayNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REP_ROUTE_WASTE_TIME.DIRECTION
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REP_ROUTE_WASTE_TIME.RUN_TIME_NUM
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    private Integer runTimeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REP_ROUTE_WASTE_TIME.WASTE_TIME
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    private Short wasteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_ROUTE_WASTE_TIME.ROUTE_ID
     *
     * @return the value of REP_ROUTE_WASTE_TIME.ROUTE_ID
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public Long getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_ROUTE_WASTE_TIME.ROUTE_ID
     *
     * @param routeId the value for REP_ROUTE_WASTE_TIME.ROUTE_ID
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public void setRouteId(Long routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_ROUTE_WASTE_TIME.RUN_DAY_NUM
     *
     * @return the value of REP_ROUTE_WASTE_TIME.RUN_DAY_NUM
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public String getRunDayNum() {
        return runDayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_ROUTE_WASTE_TIME.RUN_DAY_NUM
     *
     * @param runDayNum the value for REP_ROUTE_WASTE_TIME.RUN_DAY_NUM
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public void setRunDayNum(String runDayNum) {
        this.runDayNum = runDayNum == null ? null : runDayNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_ROUTE_WASTE_TIME.DIRECTION
     *
     * @return the value of REP_ROUTE_WASTE_TIME.DIRECTION
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_ROUTE_WASTE_TIME.DIRECTION
     *
     * @param direction the value for REP_ROUTE_WASTE_TIME.DIRECTION
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_ROUTE_WASTE_TIME.RUN_TIME_NUM
     *
     * @return the value of REP_ROUTE_WASTE_TIME.RUN_TIME_NUM
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public Integer getRunTimeNum() {
        return runTimeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_ROUTE_WASTE_TIME.RUN_TIME_NUM
     *
     * @param runTimeNum the value for REP_ROUTE_WASTE_TIME.RUN_TIME_NUM
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public void setRunTimeNum(Integer runTimeNum) {
        this.runTimeNum = runTimeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REP_ROUTE_WASTE_TIME.WASTE_TIME
     *
     * @return the value of REP_ROUTE_WASTE_TIME.WASTE_TIME
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public Short getWasteTime() {
        return wasteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REP_ROUTE_WASTE_TIME.WASTE_TIME
     *
     * @param wasteTime the value for REP_ROUTE_WASTE_TIME.WASTE_TIME
     *
     * @mbg.generated Wed Jun 26 14:53:41 CST 2019
     */
    public void setWasteTime(Short wasteTime) {
        this.wasteTime = wasteTime;
    }

    public Integer getWasteTimeInt(){
        return Convert.toInt(wasteTime);
    }
}