package com.gci.schedule.driverless.mapper;

import com.gci.schedule.driverless.bean.bs.BsEmployee;
import org.springframework.stereotype.Repository;

@Repository
public interface BsEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APTS.BS_EMPLOYEE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    int deleteByPrimaryKey(Long employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APTS.BS_EMPLOYEE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    int insert(BsEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APTS.BS_EMPLOYEE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    int insertSelective(BsEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APTS.BS_EMPLOYEE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    BsEmployee selectByPrimaryKey(Long employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APTS.BS_EMPLOYEE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    int updateByPrimaryKeySelective(BsEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APTS.BS_EMPLOYEE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(BsEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APTS.BS_EMPLOYEE
     *
     * @mbg.generated Mon Jul 11 11:24:55 CST 2022
     */
    int updateByPrimaryKey(BsEmployee record);

}